name: 'Package Cleanup Action'
description: 'This cleans up packages for GitHub based on provided inputs.'
inputs:
  packageOwner: # change this
    required: true
    description: 'Owner of the package'
  packageName: # change this
    required: true
    description: 'Name of the package'
  packageType: # change this
    required: true
    description: 'Type of the package (npm)'
    default: 'npm'
  deleteVersionRegex: # change this
    required: true
    description: 'Version regex to remove'
    default: '.*SMA-.*'
  maxAgeDays:
    required: true
    description: 'Clean packages older than X days'
    default: 14
  githubToken:
    required: true
    description: 'Github token'
  dryRun:
    required: true
    default: 'true'
    description: 'The packages list te delete will be printed. Nothing will be deleted!'
runs:
  using: 'node16'
  main: 'dist/index.js'
